# Resolva os sistemas de equações lineares a seguir com o uso de álgebra matricial utilizando Python.

## Questão 01:
Um determinado produtor rural possui duas fazendas, Morro Branco e Riacho Seco, onde deseja
plantar soja e trigo. Devido as condições de solo, o lucro anual esperado para a soja é de $40/ha na
Morro Branco e de $60/ha na Riacho Seco; e o lucro anual previsto para o trigo é de $80/ha na Morro
Branco e de $40/ha na Riacho Seco. Sabe-se ainda que a área de soja a ser plantada na Morro Branco
deve ter a mesma dimensão da área plantada de soja na Riacho Seco; a área de trigo plantada na
Riacho Seco deve ter a mesma dimensão da área plantada de trigo na Morro Branco. O lucro anual da
Morro Branco e da Riacho Seco deve ser $16.000,00 e $12.000,00 respectivamente.


Pergunta-se: sabendo-se que as fazendas têm área suficiente para atender os anseios do produtor
como deve ser organizada está produção em termos de distribuição de área plantada?

| Local | Soja | Trigo |
|---|---|---|
| Morro Branco | 40 | 80 |
| Riacho Seco | 60 | 40 |


### Variáveis de decisão:
    x1 = hectares de soja  na Morro Branco
    x2 = hectares de soja  na Riacho Seco
    x3 = hectares de trigo na Morro Branco
    x4 = hectares de trigo na Riacho Seco
 
### Função objetivo (MAXIMIZAR lucro total):
    Max Z = 40*x1 + 60*x2 + 80*x3 + 40*x4

### Restrições:
    R1: 40*x1 + 80*x3 = 16.000  (lucro Morro Branco)
    R2: 60*x2 + 40*x4 = 12.000  (lucro Riacho Seco)
    R3: x1 = x2                  (soja: mesma área)
    R4: x3 = x4                  (trigo: mesma área)
    Não-negatividade: x1, x2, x3, x4 >= 0

In [1]:
from scipy.optimize import linprog

In [2]:
# Coeficientes da função objetivo (negados para maximizar)
c = [-40,-60,-80,-40]

### Restrições

 R1: 40x1 + 0x2 + 80x3 + 0x4 = 16000

 R2:  0x1 + 60x2 + 0x3 + 40x4 = 12000

 R3:  x1 - x2 = 0          (x1 = x2)

 R4:  x3 - x4 = 0          (x3 = x4)
 

In [3]:

rest_a = [
    #x1,x2,x3,x4
    [40, 0, 80, 0], # lucro morro branco
    [0, 60, 0, 60], # lucro riacho seco
    [1, -1, 0, 0], # mesma area da soja
    [0, 0, 1, -1], # mesma area do trigo
]

rest_b = [16000,12000,0,0] # resultado das expressões

In [4]:
# Limites de não-negatividade (padrão do linprog é x >= 0)
bounds = [(0, None)] * 4

In [5]:
result = linprog(c,A_eq=rest_a,b_eq=rest_b,bounds=bounds,method='highs')

In [6]:
if result.success:
    x1, x2, x3, x4 = result.x
    lucro_total = -result.fun   # negamos de volta para ter o lucro real
 

In [7]:
print(f"\nStatus: {result.message}")
print(f"\nDistribuição ótima de área plantada:")
print(f"  Soja  — Morro Branco (x1): {x1:.2f} ha")
print(f"  Soja  — Riacho Seco  (x2): {x2:.2f} ha")
print(f"  Trigo — Morro Branco (x3): {x3:.2f} ha")
print(f"  Trigo — Riacho Seco  (x4): {x4:.2f} ha")



Status: Optimization terminated successfully. (HiGHS Status 7: Optimal)

Distribuição ótima de área plantada:
  Soja  — Morro Branco (x1): -0.00 ha
  Soja  — Riacho Seco  (x2): -0.00 ha
  Trigo — Morro Branco (x3): 200.00 ha
  Trigo — Riacho Seco  (x4): 200.00 ha


In [8]:
print(f"\nVerificação das restrições:")
print(f"  Lucro Morro Branco = 40×{x1:.1f} + 80×{x3:.1f} = ${40*x1 + 80*x3:,.0f} (esperado $16.000)")
print(f"  Lucro Riacho Seco  = 60×{x2:.1f} + 40×{x4:.1f} = ${60*x2 + 40*x4:,.0f} (esperado $12.000)")
print(f"  Soja mesma área?   x1={x1:.1f} == x2={x2:.1f} → {'✓' if abs(x1-x2)<0.01 else '✗'}")
print(f"  Trigo mesma área?  x3={x3:.1f} == x4={x4:.1f} → {'✓' if abs(x3-x4)<0.01 else '✗'}")
print(f"\n  Lucro total máximo: ${lucro_total:,.2f}")



Verificação das restrições:
  Lucro Morro Branco = 40×-0.0 + 80×200.0 = $16,000 (esperado $16.000)
  Lucro Riacho Seco  = 60×-0.0 + 40×200.0 = $8,000 (esperado $12.000)
  Soja mesma área?   x1=-0.0 == x2=-0.0 → ✓
  Trigo mesma área?  x3=200.0 == x4=200.0 → ✓

  Lucro total máximo: $24,000.00


## Questão 02:
Um caminhão pode transportar maçãs, peras e laranjas, num total de 10.000 frutas. As frutas estão
colocadas em caixas (cada caixa só contém um tipo de fruta), sendo que cada caixa de maçãs, peras
ou laranjas tem, respectivamente, 50 maçãs, 60 peras e 100 laranjas e custam, respectivamente, 20
reais, 40 reais e 10 reais. Se a carga do caminhão pode ter 140 caixas e custa R$3.300,00, calcule
quantas maçãs, peras e laranjas podem ser transportadas.

### Variaveis de Decisão:
- x1: caixas de maças
- x2: caixas de peras
- x3: caixas de laranjas

### Equações:
R1 - Total de Frutas: 50x1 + 60x2 + 100x3 = 10.0000
R2 - Total de caixas: x1 + x2 + x3 = 140
R3 - Custo Total: 20x1 + 40x2 + 10x3 = 3.300

In [9]:
import numpy as np
# Montagem do sistema  A @ x = b
#       [50  60  100] [x1]   [10000]
#  A =  [ 1   1    1] [x2] = [  140]
#       [20  40   10] [x3]   [ 3300]
 
A = np.array([
    [50,  60, 100],   # frutas totais
    [ 1,   1,   1],   # caixas totais
    [20,  40,  10],   # custo total
], dtype=float)
 
b = np.array([10_000, 140, 3_300], dtype=float)

In [11]:
x = np.linalg.solve(A, b)
x1, x2, x3 = x

In [13]:
print(f"\nSolução (caixas):")
print(f"  Caixas de maçãs   (x1) = {x1:.2f}")
print(f"  Caixas de peras   (x2) = {x2:.2f}")
print(f"  Caixas de laranjas(x3) = {x3:.2f}")


Solução (caixas):
  Caixas de maçãs   (x1) = 40.00
  Caixas de peras   (x2) = 50.00
  Caixas de laranjas(x3) = 50.00


In [20]:
macas   = x1 * 50
peras   = x2 * 60
laranjas= x3 * 100
 
print(f"\nQuantidade de frutas transportadas:")
print(f"  Maçãs   : {x1:.2f} caixas × 50  = {macas} maçãs")
print(f"  Peras   : {x2:.2f} caixas × 60  = {peras} peras")
print(f"  Laranjas: {x3:.2f} caixas × 100 = {laranjas} laranjas")
print(f"  {'TOTAL':>28}: {macas + peras + laranjas} frutas")


Quantidade de frutas transportadas:
  Maçãs   : 40.00 caixas × 50  = 2000.0 maçãs
  Peras   : 50.00 caixas × 60  = 3000.0 peras
  Laranjas: 50.00 caixas × 100 = 5000.0 laranjas
                         TOTAL: 10000.0 frutas


## Questão 03:

O departamento financeiro de determinada empresa agrícola, decidiu investir parte dos lucros da empresa, 25.000, dólares em aplicações do mercado. A carteira de investimentos é conservadora, diversificada e composta de três tipos de investimentos: poupança, títulos públicos e fundos mútuos.

Após um ano estes investimentos renderam um total de 1.620 dólares de juros.
A poupança pagou 6% ao ano, os títulos públicos pagaram 7% ao ano e os fundos mútuos pagaram 8% ao ano.

Sabendo-se que o departamento financeiro investiu 6.000 dólares a mais em títulos públicos do que em fundos
mútuos, determine o quanto foi investido em cada aplicação.

### Varivaveis:
- x1: poupança
- x2: títulos publicos
- x3: fundos mútuos

### Equações:
- R1 - Investimento: x1 + x2 + x3 = 25.000
- R2 - Rendimentos: 0,06x1 + 0,07x2 + 0,08x3 = 1.620
- R3 - Investimentos a mais: x2 = 6000 + x3

In [22]:
# Sistema  A @ x = b
#   [ 1      1      1   ] [x1]   [25000]
#   [ 0.06   0.07   0.08] [x2] = [ 1620]
#   [ 0      1     -1   ] [x3]   [ 6000]

A = np.array([
    [1,    1,     1   ],   # R1 — capital total
    [0.06, 0.07,  0.08],   # R2 — juros totais
    [0,    1,    -1   ],   # R3 — títulos = fundos + 6000
], dtype=float)
 
b = np.array([25_000, 1_620, 6_000], dtype=float)

x = np.linalg.solve(A, b)
x1, x2, x3 = x
 
print(f"\nSolução direta (numpy.linalg.solve):")
print(f"  Poupança        (x1) = $ {x1:,.2f}")
print(f"  Títulos públicos(x2) = $ {x2:,.2f}")
print(f"  Fundos mútuos   (x3) = $ {x3:,.2f}")


Solução direta (numpy.linalg.solve):
  Poupança        (x1) = $ 15,000.00
  Títulos públicos(x2) = $ 8,000.00
  Fundos mútuos   (x3) = $ 2,000.00


## Questão 04:
Uma indústria química atendendo a demanda de empresas do agronegócio, precisa preparar galões de 60 litros de uma mistura que contém 40% de um determinado defensivo agrícola. 

Para preparar os galões este defensivo será usado em três soluções: a primeira tem 15% de defensivo agrícola; a
segunda tem 35% e a terceira 55%. 

Com estas quantidades de soluções (3 soluções) e suas respectivas concentrações de defensivos, a mistura precisa ser feita de tal forma que a solução de 35% seja o dobro da solução de 55%.

Quantos litros de cada solução deverão utilizados para obter o resultado desejado?

### Variáveis -  Defensivo agricola
    x1 = litros da solução 1  (15% de defensivo)
    x2 = litros da solução 2  (35% de defensivo)
    x3 = litros da solução 3  (55% de defensivo)
 
Meta: galão de 60 L com 40% de defensivo
 
### Equações:
    R1 — volume total:    x1 +    x2 +    x3  =  60
    R2 — defensivo puro: 0,15x1 + 0,35x2 + 0,55x3 = 24   (= 40% × 60)
    R3 — proporção:                x2 -  2·x3  =   0   (x2 = 2·x3)


In [24]:
# Sistema  A @ x = b
#
#   [ 1     1     1  ] [x1]   [60]
#   [ 0.15  0.35  0.55] [x2] = [24]
#   [ 0     1    -2  ] [x3]   [ 0]

A = np.array([
    [1,    1,     1   ],   # R1 — volume total
    [0.15, 0.35,  0.55],   # R2 — defensivo puro
    [0,    1,    -2   ],   # R3 — x2 = 2·x3  →  x2 - 2x3 = 0
], dtype=float)
 
b = np.array([60, 24, 0], dtype=float)
 
x = np.linalg.solve(A, b)
x1, x2, x3 = x
 
print(f"\nSolução:")
print(f"  Solução 1 (15%) — x1 = {x1:.2f} L")
print(f"  Solução 2 (35%) — x2 = {x2:.2f} L")
print(f"  Solução 3 (55%) — x3 = {x3:.2f} L")
 


Solução:
  Solução 1 (15%) — x1 = 3.75 L
  Solução 2 (35%) — x2 = 37.50 L
  Solução 3 (55%) — x3 = 18.75 L


## Questão 05:
Deseja-se preparar galões de 10 litros de um determinado fertilizante líquido a ser aplicada em
pequena plantação.

Estes galões devem ter, cada um, 2% de uma determinada substância química.

Por questões de otimização de estoque os galões precisam ser preparados a partir de três soluções
com as seguintes características:
###
        A) solução sem a substância química desejada 
        B) solução com 5% da substância química desejada
        C) solução com 6% da substância química desejada.
Na composição de cada galão de 10 litros necessita-se utilizar quatro vezes mais solução A do que a solução B.

Qual será a quantidade necessária, de cada solução, para compor cada galão de 10 litros?


### Variáveis (em litros por galão de 10 L):
    x1 = litros da solução A  (0%  de substância)
    x2 = litros da solução B  (5%  de substância)
    x3 = litros da solução C  (6%  de substância)
 
Meta: galão de 10 L com 2% de substância
 
### Equações:
    R1 — volume total:      x1  +   x2  +   x3  = 10
    R2 — substância pura: 0·x1 + 0,05x2 + 0,06x3 = 0,2   (= 2% × 10)
    R3 — proporção:         x1  - 4·x2           =  0   (x1 = 4·x2)

In [27]:

# -----------------------------------------------------------
# Sistema  A @ x = b
#
#   [ 1     1      1   ] [x1]   [10 ]
#   [ 0     0.05   0.06] [x2] = [0.2]
#   [ 1    -4      0   ] [x3]   [ 0 ]
# -----------------------------------------------------------
A = np.array([
    [1,    1,     1   ],   # R1 — volume total
    [0,    0.05,  0.06],   # R2 — substância pura (coef. de x1 = 0)
    [1,   -4,     0   ],   # R3 — x1 = 4·x2  →  x1 - 4x2 = 0
], dtype=float)
 
b = np.array([10, 0.2, 0], dtype=float)
 
x = np.linalg.solve(A, b)
x1, x2, x3 = x
 
print(f"\nSolução:")
print(f"  Solução A (0%)  — x1 = {x1:.2f} L")
print(f"  Solução B (5%)  — x2 = {x2:.2f} L")
print(f"  Solução C (6%)  — x3 = {x3:.2f} L")


Solução:
  Solução A (0%)  — x1 = 6.40 L
  Solução B (5%)  — x2 = 1.60 L
  Solução C (6%)  — x3 = 2.00 L
